package exceptions_article_second_part;

public class App4 {
    public static void main(String[] args) throws Exception { // пугаем
        // но ничего не бросаем
    }
}
